import prisma from "../src/config/prisma.js";

async function seedMenu() {
    console.log("🍽️ Seeding Swapee’s Kitchen menu...");

    const items = [
        // ---------------- CURRY ----------------
        {
            name: "Paneer Butter Masala",
            price: 159,
            description: "Creamy tomato gravy with soft paneer cubes",
            imageUrl: "https://res.cloudinary.com/demo/image/upload/paneer_butter_masala.jpg",
            type: "FOOD",
            category: "Curry",
            nutritionInfo: { calories: 320, protein: "12g", fat: "18g" },
        },
        {
            name: "Sev Bhaji",
            price: 159,
            description: "Spicy Rajasthani curry topped with sev",
            imageUrl: "https://res.cloudinary.com/demo/image/upload/sev_bhaji.jpg",
            type: "FOOD",
            category: "Curry",
            nutritionInfo: { calories: 290, carbs: "24g" },
        },
        {
            name: "Shahi Paneer",
            price: 159,
            description: "Royal paneer curry with rich cashew gravy",
            imageUrl: "https://res.cloudinary.com/demo/image/upload/shahi_paneer.jpg",
            type: "FOOD",
            category: "Curry",
            nutritionInfo: { calories: 340, protein: "13g" },
        },
        {
            name: "Paneer Bhurji",
            price: 159,
            description: "Crumbled paneer cooked with onions & spices",
            imageUrl: "https://res.cloudinary.com/demo/image/upload/paneer_bhurji.jpg",
            type: "FOOD",
            category: "Curry",
            nutritionInfo: { calories: 310, protein: "14g" },
        },
        {
            name: "Kadhai Paneer",
            price: 149,
            description: "Paneer cooked with capsicum in kadhai masala",
            imageUrl: "https://res.cloudinary.com/demo/image/upload/kadhai_paneer.jpg",
            type: "FOOD",
            category: "Curry",
            nutritionInfo: { calories: 300, protein: "12g" },
        },
        {
            name: "Kadhi Pakora",
            price: 119,
            description: "Yogurt-based kadhi with pakoras",
            imageUrl: "https://res.cloudinary.com/demo/image/upload/kadhi_pakora.jpg",
            type: "FOOD",
            category: "Curry",
            nutritionInfo: { calories: 260 },
        },
        {
            name: "Masala Bhaat",
            price: 119,
            description: "Spiced rice cooked Maharashtrian style",
            imageUrl: "https://res.cloudinary.com/demo/image/upload/masala_bhaat.jpg",
            type: "FOOD",
            category: "Curry",
            nutritionInfo: { calories: 280, carbs: "45g" },
        },
        {
            name: "Mix Veg",
            price: 119,
            description: "Seasonal vegetables cooked in homestyle gravy",
            imageUrl: "https://res.cloudinary.com/demo/image/upload/mix_veg.jpg",
            type: "FOOD",
            category: "Curry",
            nutritionInfo: { calories: 220 },
        },
        {
            name: "Dal Tadka",
            price: 99,
            description: "Yellow dal tempered with ghee & spices",
            imageUrl: "https://res.cloudinary.com/demo/image/upload/dal_tadka.jpg",
            type: "FOOD",
            category: "Curry",
            nutritionInfo: { calories: 210, protein: "9g" },
        },

        // ---------------- SNACKS ----------------
        {
            name: "Paneer Sandwich",
            price: 99,
            description: "Grilled sandwich stuffed with paneer",
            imageUrl: "https://res.cloudinary.com/demo/image/upload/paneer_sandwich.jpg",
            type: "FOOD",
            category: "Snacks",
            nutritionInfo: { calories: 260 },
        },
        {
            name: "Aloo Sandwich",
            price: 59,
            description: "Spiced potato sandwich",
            imageUrl: "https://res.cloudinary.com/demo/image/upload/aloo_sandwich.jpg",
            type: "FOOD",
            category: "Snacks",
            nutritionInfo: { calories: 220 },
        },
        {
            name: "Veg Sandwich",
            price: 79,
            description: "Fresh vegetable sandwich",
            imageUrl: "https://res.cloudinary.com/demo/image/upload/veg_sandwich.jpg",
            type: "FOOD",
            category: "Snacks",
            nutritionInfo: { calories: 200 },
        },
        {
            name: "Poha",
            price: 49,
            description: "Light and healthy flattened rice snack",
            imageUrl: "https://res.cloudinary.com/demo/image/upload/poha.jpg",
            type: "FOOD",
            category: "Snacks",
            nutritionInfo: { calories: 180 },
        },

        // ---------------- PARANTHA / RICE ----------------
        {
            name: "Paneer Parantha",
            price: 89,
            description: "Stuffed parantha with paneer filling",
            imageUrl: "https://res.cloudinary.com/demo/image/upload/paneer_parantha.jpg",
            type: "FOOD",
            category: "Parantha & Rice",
            nutritionInfo: { calories: 290 },
        },
        {
            name: "Aloo Pyaaz Parantha",
            price: 59,
            description: "Parantha stuffed with potato & onion",
            imageUrl: "https://res.cloudinary.com/demo/image/upload/aloo_pyaaz_parantha.jpg",
            type: "FOOD",
            category: "Parantha & Rice",
            nutritionInfo: { calories: 270 },
        },
        {
            name: "Pyaaz Parantha",
            price: 59,
            description: "Onion-stuffed parantha",
            imageUrl: "https://res.cloudinary.com/demo/image/upload/pyaaz_parantha.jpg",
            type: "FOOD",
            category: "Parantha & Rice",
            nutritionInfo: { calories: 260 },
        },
        {
            name: "Plain Parantha",
            price: 39,
            description: "Classic plain parantha",
            imageUrl: "https://res.cloudinary.com/demo/image/upload/plain_parantha.jpg",
            type: "FOOD",
            category: "Parantha & Rice",
            nutritionInfo: { calories: 230 },
        },
        {
            name: "Roti",
            price: 10,
            description: "Simple wheat roti",
            imageUrl: "https://res.cloudinary.com/demo/image/upload/roti.jpg",
            type: "FOOD",
            category: "Parantha & Rice",
            nutritionInfo: { calories: 80 },
        },
        {
            name: "Butter Roti",
            price: 15,
            description: "Roti topped with butter",
            imageUrl: "https://res.cloudinary.com/demo/image/upload/butter_roti.jpg",
            type: "FOOD",
            category: "Parantha & Rice",
            nutritionInfo: { calories: 100 },
        },
        {
            name: "Jeera Rice",
            price: 99,
            description: "Fragrant basmati rice with cumin",
            imageUrl: "https://res.cloudinary.com/demo/image/upload/jeera_rice.jpg",
            type: "FOOD",
            category: "Parantha & Rice",
            nutritionInfo: { calories: 250 },
        },
        {
            name: "Paneer Pulao",
            price: 139,
            description: "Rice cooked with paneer and spices",
            imageUrl: "https://res.cloudinary.com/demo/image/upload/paneer_pulao.jpg",
            type: "FOOD",
            category: "Parantha & Rice",
            nutritionInfo: { calories: 320, protein: "11g" },
        },

        // ---------------- FRUITS: 4 Cut Fruits ----------------
        {
            name: "Fresh Seasonal Fruit Bowl",
            price: 199,
            description: "Mixed seasonal fruits freshly cut",
            imageUrl: "https://res.cloudinary.com/demo/image/upload/fruit_bowl.jpg",
            type: "FRUIT",
            category: "Fresh Cut",
            nutritionInfo: { calories: 120 },
        },
        {
            name: "Watermelon Cubes",
            price: 99,
            description: "Sweet chilled watermelon cubes",
            imageUrl: "https://res.cloudinary.com/demo/image/upload/watermelon.jpg",
            type: "FRUIT",
            category: "Fresh Cut",
            nutritionInfo: { calories: 80 },
        },
        {
            name: "Papaya Bowl",
            price: 119,
            description: "Ripe papaya chunks",
            imageUrl: "https://res.cloudinary.com/demo/image/upload/papaya.jpg",
            type: "FRUIT",
            category: "Fresh Cut",
            nutritionInfo: { calories: 90 },
        },
        {
            name: "Pineapple Wedges",
            price: 129,
            description: "Freshly sliced pineapple wedges",
            imageUrl: "https://res.cloudinary.com/demo/image/upload/pineapple.jpg",
            type: "FRUIT",
            category: "Fresh Cut",
            nutritionInfo: { calories: 85 },
        },

        // ---------------- FRUITS: 10 Whole Fruits ----------------
        {
            name: "Premium Apples (2 pcs)",
            price: 129,
            description: "Crunchy Red Delicious apples",
            imageUrl: "https://res.cloudinary.com/demo/image/upload/apple.jpg",
            type: "FRUIT",
            category: "Whole Fruits",
            nutritionInfo: { calories: 95 },
        },
        {
            name: "Banana Bunch (6 pcs)",
            price: 60,
            description: "Fresh Robusta bananas",
            imageUrl: "https://res.cloudinary.com/demo/image/upload/banana.jpg",
            type: "FRUIT",
            category: "Whole Fruits",
            nutritionInfo: { calories: 105 },
        },
        {
            name: "Nagpur Oranges (3 pcs)",
            price: 89,
            description: "Sweet and juicy Nagpur oranges",
            imageUrl: "https://res.cloudinary.com/demo/image/upload/orange.jpg",
            type: "FRUIT",
            category: "Whole Fruits",
            nutritionInfo: { calories: 60 },
        },
        {
            name: "Pomegranate (2 pcs)",
            price: 149,
            description: "Freshly picked quality pomegranates",
            imageUrl: "https://res.cloudinary.com/demo/image/upload/pomegranate.jpg",
            type: "FRUIT",
            category: "Whole Fruits",
            nutritionInfo: { calories: 230 },
        },
        {
            name: "Green Grapes (500g)",
            price: 99,
            description: "Seedless sweet green grapes",
            imageUrl: "https://res.cloudinary.com/demo/image/upload/grapes.jpg",
            type: "FRUIT",
            category: "Whole Fruits",
            nutritionInfo: { calories: 150 },
        },
        {
            name: "Black Grapes (500g)",
            price: 119,
            description: "Seedless juicy black grapes",
            imageUrl: "https://res.cloudinary.com/demo/image/upload/black_grapes.jpg",
            type: "FRUIT",
            category: "Whole Fruits",
            nutritionInfo: { calories: 160 },
        },
        {
            name: "Guava (2 pcs)",
            price: 69,
            description: "Fresh farm-picked guava",
            imageUrl: "https://res.cloudinary.com/demo/image/upload/guava.jpg",
            type: "FRUIT",
            category: "Whole Fruits",
            nutritionInfo: { calories: 70 },
        },
        {
            name: "Pear (2 pcs)",
            price: 110,
            description: "Sweet and soft imported pears",
            imageUrl: "https://res.cloudinary.com/demo/image/upload/pear.jpg",
            type: "FRUIT",
            category: "Whole Fruits",
            nutritionInfo: { calories: 100 },
        },
        {
            name: "Kiwi (3 pcs)",
            price: 180,
            description: "Zespri Green Kiwis",
            imageUrl: "https://res.cloudinary.com/demo/image/upload/kiwi.jpg",
            type: "FRUIT",
            category: "Whole Fruits",
            nutritionInfo: { calories: 90 },
        },
        {
            name: "Sweet Lime / Mosambi (4 pcs)",
            price: 95,
            description: "Fresh Mosambi for juicing or eating",
            imageUrl: "https://res.cloudinary.com/demo/image/upload/mosambi.jpg",
            type: "FRUIT",
            category: "Whole Fruits",
            nutritionInfo: { calories: 50 },
        }
    ];

    const existing = await prisma.menuItem.count();
    if (existing > 0) {
        console.log("Deleted existing menu items...", await prisma.menuItem.deleteMany());
    }

    await prisma.menuItem.createMany({
        data: items,
        skipDuplicates: true,
    });

    console.log(`✅ Seeded ${items.length} menu items`);
}

seedMenu()
    .catch(console.error)
    .finally(() => prisma.$disconnect());
